// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'FlexCenterHorizontal': string;
  'FlexCenterVertical': string;
  'FlexRight': string;
  'PageContainer': string;
  'PageHead': string;
  'SaveButton': string;
  'Wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
