// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CircleStatusError': string;
  'CircleStatusOK': string;
  'Icon-spin': string;
  'PanelContainer': string;
  'PanelWrapper': string;
  'RefreshIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
