// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ErrorIcon': string;
  'Icon-spin': string;
  'LoadingContainer': string;
  'RefreshIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
